services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth:
    build: ./services/auth
    environment:
      PORT: 8001
      DB_DSN: ${POSTGRES_DSN}
      DB_SCHEMA: auth
      JWT_SECRET: ${JWT_SECRET}
    ports: ["8001:8001"]
    depends_on:
      postgres: { condition: service_healthy }

  catalog:
    build: ./services/catalog
    environment:
      PORT: 8002
      DB_DSN: ${POSTGRES_DSN}
      DB_SCHEMA: catalog
    ports: ["8002:8002"]
    depends_on:
      postgres: { condition: service_healthy }

  booking:
    build: ./services/booking
    environment:
      PORT: 8003
      DB_DSN: ${POSTGRES_DSN}
      DB_SCHEMA: booking
    ports: ["8003:8003"]
    depends_on:
      postgres:
        condition: service_healthy

  payment:
    build: ./services/payment
    environment:
      PORT: 8004
      DB_DSN: ${POSTGRES_DSN}
      DB_SCHEMA: payment
      MIDTRANS_CLIENT_KEY: ${MIDTRANS_SERVER_KEY}
      MIDTRANS_ENV: sandbox
    ports: ["8004:8004"]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata: {}
